twilio/twilio-voice-react-native

CHANGELOG.md, api/voice-react-native-sdk.api.md, src/Call.tsx, src/Voice.tsx
This PR fixes references and type exports from the incorrect `addEventListener` to the correct `addListener`.
- Change `addEventListener` in `Call.tsx`
- Change `addEventListener` in `Voice.tsx`
- Test that the app properly binds to the `EventEmitter` objects using the `test-application` and the "new" `addListener` call signature.
- VSCode properly detects docstrings and Intellisense for the "new" function signatures.
- The public API rollup has the "new" function signatures.
Tested on Android, cannot personally test on iOS but the iOS e2e tests pass.
=> [VBLOCKS-1115] fix: rename references to addEventListener to addListener

android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java, ios/TwilioVoiceReactNative+CallKit.m
Removed frontline specific comment around `displayName`. Added a generic blurb about how `displayName` can be used when passed as a custom param.
- No code change
=> VBLOCKS-1357: Added a generic blurb about how displayName can be used when passed as a custom param

ios/TwilioVoiceReactNative.m
The iOS SDK throws an exception when the device token argument is `nil`. In some cases the PushKit device token might not be ready when the app calls the `register()` method and exceptions will be raised by the iOS SDK, which is not really a good UX.
- Reject the promise with explanation message instead of letting the SDK throw the exception
- CircleCI
=> VBLOCKS - Reject the promise before the invalid device token exception is raised

README.md, ios/TwilioVoiceReactNative.m, test/app/ios/TwilioVoiceReactNativeExample/AppDelegate.m
Move iOS PushKit initialization into the `TwilioVoiceReactNative` native module and correct the order of event notification-observation and device token update.
The original guideline from the Voice iOS SDK quickstart initializes the PushKit instance in AppDelegate to ensure push notifications and CallKit VoIP incoming calls work properly (especially when the app is not running). Turns out having the PushKit registry instance in the `TwilioVoiceReactNative` module also guarantees the app to be launched and respond to the incoming notification without violating the iOS PushKit/CallKit policy.
- Move …
=> Manage iOS PushKit instance in the iOS TwilioVoiceReactNative native module

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java, src/common.ts
JIRA Ticket https://issues.corp.twilio.com/browse/VBLOCKS-1238
This PR fixes the warning about instantiating a `NativeEventEmitter` with an argument that lacks an `addListener` and `removeListener` method. Perhaps outdated, the official RN docs recommend constructing a `NativeEventEmitter` by passing the `NativeModule` as an argument, but the TS types show that we can opt out of passing anything at all.
- Alter construction of the `NativeEventEmitter`.
- Tested event propagation from the native layer to the JS layer.
N/A
=> [VBLOCKS-1238] fix(js): native event emitter

CHANGELOG.md, COMMON_ISSUES.md, android/build.gradle, android/src/main/java/com/twiliovoicereactnative/AudioSwitchManager.java, android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java, android/src/main/java/com/twiliovoicereactnative/IncomingCallNotificationService.java, android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java, android/src/main/java/com/twiliovoicereactnative/ReactNativeArgumentsSerializer.java, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativePackage.java, android/src/main/java/com/twiliovoicereactnative/VoiceBroadcastReceiver.java
This PR updates the required API for the codebase and removes `RequiresApi`. `.forEach` invocations that required API level `24` have been reverted to a more traditional `for each` loop.
This PR also adds `Intent` flags necessary for higher versions of Android.
- Add `Intent` flags.
- Remove `RequiresApi` decorators.
- Revert `for each` loops.
- Ran test app and made client-to-client and client-to-PSTN calls outgoing calls, and incoming client-to-client and PSTN-to-client calls.
- Ran unit tests.
N/A
=> [VBLOCKS-1237] Android 12 updates.

CHANGELOG.md, api/voice-react-native-sdk.api.md, src/Voice.tsx, src/__tests__/Voice.test.ts
This PR changes the custom parameter type to a more restrictive `Record<string, string>` instead of `Record<string, any>`. Note that Android would support `Record<string, boolean | number | string>` but iOS cannot. However, Android will convert `boolean | number | string` into `string` using string representations of the former two, so `Record<string, string>` loses no functionality.
- Change connect function signature.
- Add changelog entry.
- Typescript compiles.
Not a lot of testing was done considering it's a type change, only validated by ensuring Typescript compilation.
=> [VBLOCKS-1486] fix(js): custom parameter type

android/build.gradle, android/src/main/java/com/twiliovoicereactnative/IncomingCallNotificationService.java, android/src/main/java/com/twiliovoicereactnative/NotificationProxyActivity.java, android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java, test/app/android/app/src/main/AndroidManifest.xml, test/app/android/build.gradle
Due to a change on Android 31, services can no longer launch applications and as such, our application could not awake due to notifications. This was fixed by making a proxy activity that interfaces with the service but also receives notification intents, which it can then use to launch other activities.
- added a invisible activity which acts as a broker between the service and the main application
- Modified notifications to route to the invisible activity
- Tested that reacting to an in coming call launches the app
=> VBLOCKS-1595: fixed application so that notifications can awake (Android 31)

test/app/ios/Podfile, test/app/ios/Podfile.lock, twilio-voice-react-native.podspec
Freeze iOS voice SDK dependency on v6.6.0
Update the handleNotificationMethod
Fix bug preventing project from compiling
- Update the voice SDK depency to 6.6.0
- Freeze the iOS voice SDK dependency in the podspec
- Confirmed app built with new framework version
=> VBLOCKS-1682 Add fix to freeze iOS voice SDK dependency

android/src/main/java/com/twiliovoicereactnative/AudioSwitchManager.java, constants/constants.src, ios/TwilioVoiceReactNative.m
Move audio device types to common constants
- New common constants for audio device types
- Update iOS audio device logic
- Update Android audio device constant variables
- Ran app and listed audio devices locally 
=> VBLOCKS-1787 Move audio device types to common constants

CHANGELOG.md, ios/TwilioVoiceReactNative.m
Fixed an issue when switching from Bluetooth to earpiece does not have any effect or error on iOS. Turns out the audio-port override at the end of the device selection function is only needed when switching to the speaker.
- Only do audio port override when switching to the speaker
- Ran call test and tried switching between speaker, earpiece and Bluetooth
=> VBLOCKS-2012 Switching from Bluetooth to iPhone earpiece

.circleci/config.yml, CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java, android/src/main/java/com/twiliovoicereactnative/ReactNativeArgumentsSerializer.java, android/src/main/java/com/twiliovoicereactnative/Storage.java, api/voice-react-native-sdk.api.md, constants/constants.src, ios/TwilioVoiceReactNative+CallKit.m, ios/TwilioVoiceReactNative.h, ios/TwilioVoiceReactNative.m, package.json, src/Call.tsx, src/__mocks__/Call.ts, src/__tests__/Call.test.ts, src/type/Call.ts, test/app/src/hook.ts, test/app/src/type.ts
This PR introduces `Call.getInitialConnectedTimestamp` (milliseconds since epoch)` and the native layer support for it. Also introduces `Call.State` caching on the native layer.
Minor fixes include better CI and precommit checks.
- Android changes to serialize the call state and cache the initial connected timestamp.
- iOS changes for the above.
- JS changes for the above.
- Improve checks.
- Manually tested using the test app on Android and on iOS.
N/A
=> [VBLOCKS-1913] Persist extra call info

ios/TwilioVoiceReactNative+CallKit.m
longlong value for millisecond timestamp (iOS call initial-connected-timestamp)
- Convert timestamp to longlong value
- Ran and printed the longlong (millisecond) value to the log
=> VBLOCKS-2086 longlong value for millisecond timestamp (iOS call initial-connected-timestamp)

CHANGELOG.md, ios/TwilioVoiceReactNative+CallInvite.m
(iOS) Performing the CallKit end-call action while the UUID of the call invite is still in the map will result in an extra invite-rejected event (#211 )
- Remove from call-invite map before performing CallKit end-call action
- Mention bugfix in changelog
- Validated behavior locally
=> VBLOCKS-2080 Remove canceled call invite before ending CallKit call

CHANGELOG.md, ios/TwilioVoiceReactNative.m
The iOS native layer is not firing the `registered` and `unregistered` events when the requests are done. Adding the event emitting before resolving the promise.
=> VBLOCKS-2222 Fire registered and unregistered events when the requests are done

android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java, constants/constants.src, scripts/constants.js
Added the ability to override the SDK version for insights publishing
- Modified such that version is overridden by package.json
- Made it use Constants.src so that its a platform neutral way.
- None
=> VBLOCKS-1067: Added  sdk version override

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/IncomingCallNotificationService.java, android/src/main/java/com/twiliovoicereactnative/Storage.java, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java, android/src/main/java/com/twiliovoicereactnative/VoiceBroadcastReceiver.java
Improved such that there exists one code path for the call-rejected messages and verified that indeed, when the activity is running, an event is fired for call-rejected. _**NOTE: Without redesigning the SDK, there is no way to have the JS layer receive the event when the activity is minimized.**_
- Cleaned up message flow for call-invite-rejected events. This is similar to what was done for call accepted.
- Verified best possible behavior is available.
- Ran both test cases, call invite with application foregrounded, and with application backgrounded.
None
=> VBLOCKS-2093: Improved handling of call invite rejected, one code path now

CHANGELOG.md, ios/TwilioVoiceReactNative.m
This PR removes potentially null values from the various info messages we send to the JS layer.
- Parse through the native iOS layer to see where we send events to the JS layer.
- Find potentially null values and gate sending them to the JS layer.
- Tested on a real iOS device using the test app.
N/A
=> [VBLOCKS-2450] fix(ios): do not send explicit null

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/ReactNativeArgumentsSerializer.java
Updated JS representation of call time to be in RFC-822 format instead of double
- Changed JS seralizer for call date-time
- look above
None
=> VBLOCKS-2474: call timestamp now uses rfc-822 datetime format

CHANGELOG.md, ios/TwilioVoiceReactNative+CallKit.m, ios/TwilioVoiceReactNative.h, ios/TwilioVoiceReactNative.m
RFC-822 formatted date time string for call initial connected timestamp
- Built and ran test app locally. Formatted string `Mon, 29 Jan 2024 14:01:52 -0800`
=> VBLOCKS-2475 RFC-822 formatted date time string for call initial connected timestamp

CHANGELOG.md, src/Call.tsx, src/__mocks__/Call.ts, src/type/Call.ts, test/app/e2e/call.test.ts, test/app/src/App.tsx
This PR fixes missing call quality events by properly using the common constants to key the native info objects that are passed to the JS layer.
- Use common constants to key the native info objects.
- Manually tested with the test app.
N/A
=> [VBLOCKS-2479] fix(js): use common constants for keying quality warnings

ios/TwilioVoiceReactNative+CallKit.m
[VBLOCKS-2789](https://issues.corp.twilio.com/browse/VBLOCKS-2789)
Needed to add callMessageDelegate to CallKit
- Manual testing as Callee and Caller for "messageSent" and "messageReceived"
=> [VBLOCKS-2789] fix: add callmessagedelegate to callkit

test/app/ios/TwilioVoiceReactNativeExample/Info.plist
This PR adds the new privacy microphone usage string that newer versions of iOS mandate.
- Add usage string to Info in XCode.
- N/A
I was personally unable to test since my iOS device is on an older version of iOS that does not need this fix. However, consulting @kpchoy about this, this is exactly what his device needed to function.
=> [VBLOCKS-2787] fix: add mic privacy usage string

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/Constants.java, android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java, ios/TwilioVoiceReactNative+CallKit.m
This PR removes the custom display name TwiML parameter functionality, such that passing "displayName" as a TwiML parameter will override the notification.
- Remove the functionality.
- Tested manually with the test app.
The following scenarios were tested using the test app:
```
[x] android
[x] incoming call with twiml param
[x] native accept
[x] local disconnect
[x] remote disconnect
[x] native reject
[x] js accept
[x] local disconnect
[x] remote disconnect
[x] js reject
[x] cancel
[x] incoming call without twiml param
[x] native accept
[x] local disconnect
[x] remote disconnect
[x] native reject
[x] js accept
[x] …
```
=> [VBLOCKS-2830] Remove custom twiml parameter displayName functionality

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/ReactNativeArgumentsSerializer.java, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java, android/src/main/java/com/twiliovoicereactnative/VoiceService.java, api/voice-react-native-sdk.api.md, package.json, scripts/errors.js, src/CallInvite.tsx, src/Voice.tsx, src/__tests__/CallInvite.test.ts, src/__tests__/Voice.test.ts, src/__tests__/error/generated.test.ts, src/error/generated.ts, src/error/index.ts, test/app/src/hook.ts, yarn.lock
This PR implements a missing permissions error on Android platforms. As well as catching said error on the JS layer.
- Emit the missing permissions error in the Android layer.
- Catch the error on the JS layer.
- Add test app code path to catch and verify error.
- Manual testing with test app.
N/A
=> [VBLOCKS-3113] Catch and emit missing permissions android

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/JSEventEmitter.java, test/app/e2e/common/logParser.ts, test/app/e2e/common/rtcStatsValidators.ts, test/app/e2e/suites/call.test.ts, test/app/e2e/suites/callMessage.test.ts
This PR implements e2e tests for RTC Stats. It also fixes some missing values that are reported from the native layer as `long` values.
- Add e2e tests for RTC Stats.
- Fix `long` typed values being ignored when raised by the native layer to the JS layer on Android.
- New e2e test.
- Manual testing.
N/A
=> [VBLOCKS-2978] fix: missing android rtc byte stats

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java, android/src/main/java/com/twiliovoicereactnative/Constants.java, android/src/main/java/com/twiliovoicereactnative/VoiceService.java
Fixed API 34 notification crash when activity is not running in foreground or background.
- Now the incoming call notification does not cause foregrounding of the call service.
- Tested handling incoming calls when app is foregrounded and backgrounded.
None
=> [VBLOCKS-3421] fixed api 34 notification issue when app is backgrounded

CHANGELOG.md, android/build.gradle, android/src/main/java/com/twiliovoicereactnative/VoiceService.java, test/app/android/build.gradle
This PR bumps the `minSdkVersion` to `23` to match latest RN requirements. This PR also implements a fix for cancelling active call notifications when a call is disconnected.
- Bump `minSdkVersion` to `23`.
- Cancel call notification for disconnected calls.
- Manual testing with example app.
```
device running android api 34
outgoing call
accepted
[x] disconnected by remote
[x] disconnected by local js
[x] disconnected by local native
[x] rejected by remote
cancelled by local
[x] js
[x] native
incoming call
closed
[x] tap on notification body
accepted by local native
[x] disconnected by local js
[x] disconnected by …
```
=> Bump min sdk version and cancel notification for disconnected calls

CHANGELOG.md, src/Call.tsx, src/CallInvite.tsx, src/CallMessage/CallMessage.ts, src/__tests__/Call.test.ts, src/__tests__/CallInvite.test.ts, src/__tests__/CallMessage/CallMessage.test.ts, src/__tests__/CallMessage/IncomingCallMessage.test.ts, src/__tests__/CallMessage/OutgoingCallMessage.test.ts
This PR conditionally stringifys the content of outgoing call messages.
- Conditionally stringify content.
- Add unit tests.
- Manually tested with test app.
- Unit tests.
- Call message e2e tests are green.
N/A
=> [VBLOCKS-3468] Conditional stringify of call message content

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/VoiceService.java
Protected against case where the system recreates the service without sending it an intent. PLEASE NOTE: Could not reproduce the issue, just added a protection to prevent crashes.
- NONE
- Checks for null intent
None
=> [VBLOCKS-3603] protect against case where intent is NULL

.circleci/config.yml
This PR uses adds QE Voice React RC tests trigger to the CCI config
- Added `trigger-qe-tests` job, that will trigger two workflows in `sdks-qe-voice-react-native-slave` with default setting and custom android messaging
- Run `trigger-qe-tests` job in `build-test-release` workflow
N/A
N/A
=> [QSDK-10180] Add QE tests CCI trigger to run RC validation job after releasing new version

CHANGELOG.md, android/build.gradle, test/app/ios/Podfile.lock, twilio-voice-react-native.podspec
This PR updates the native SDK versions used by the RN SDK.
- Update native SDKs.
- Manually tested with the test app both on iOS and Android.
N/A
=> [VBLOCKS-3881] feat: update native sdk versions

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
This PR changes the way that the RN Module invokes any Voice Service API, issuing invocations on the main thread to avoid race conditions. Note that the Voice Android SDK contract necessitates all invocations occur from the main thread, so this PR is necessary to adhere to Voice Android SDK standards.
- Create a main thread handler and runnable for all applicable RNModule methods.
- Manually tested with the test app locally.
- Integration tests pass.
N/A
=> [VBLOCKS-4100] fix: invoke voice service api from main thread

.circleci/config.yml, package.json, test/app/.detoxrc.js, test/app/package.json
This PR fixes the package manifests for the SDK and the test app to work in CircleCI.
- Remove SDK eslint from analyzing the test app src folder.
- Add missing detox scripts to the test app.
- CircleCI runs and succeeds.
N/A
=> [VBLOCKS-3981] fix: add missing detox scripts

CHANGELOG.md, android/src/main/java/com/twiliovoicereactnative/ConfigurationProperties.java, android/src/main/java/com/twiliovoicereactnative/Constants.java, android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java, ios/TwilioVoiceReactNative+CallKit.m, ios/TwilioVoiceReactNative.h, ios/TwilioVoiceReactNative.m
This PR fixes an issue where the call contact handle template could be null when the JS runtime is not initialized.
- Add caching of contact handle template value to native layers.
- Manually tested with test app.
N/A
=> [VBLOCKS-4518] Task/save contact handle to preferences

CHANGELOG.md, android/build.gradle, android/src/main/AndroidManifest.xml, test/app/android/app/src/main/java/com/example/twiliovoicereactnative/MainActivity.kt
JIRA Link: https://twilio-engineering.atlassian.net/browse/VBLOCKS-4180
This PR introduces a fix from @afalls-twilio for the test app and updates the audioswitch dependency to the latest version to fix missing bluetooth devices on Android devices.
- Fix test app permissions due to an improper override. Thanks @afalls-twilio for the fix.
- Update Audioswitch dependency to fix missing Bluetooth devices on first-start on Android.
- Manual testing.
N/A
=> [VBLOCKS-4180] fix: update audioswitch and fix override in test app

ios/TwilioVoiceReactNative+PreflightTest.m, ios/TwilioVoiceReactNative.h, src/PreflightTest.ts, src/type/NativeModule.ts
This PR fixes the invocation and uses the parsed PreflightOptions from the JS layer.
- Change function invocation from `runPreflightTestWithAccessToken` to `runPreflightTestWithOptions`.
- N/A
N/A
=> [VBLOCKS-4865] Fix preflight ios events and options

CHANGELOG.md, android/build.gradle, android/src/main/java/com/twiliovoicereactnative/ConfigurationProperties.java, android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java, android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java, android/src/main/res/values/config.xml, api/voice-react-native-sdk.api.md, src/Voice.tsx, src/__mocks__/common.ts, src/__tests__/Voice.test.ts, src/type/NativeModule.ts, test/app/src/hook.ts
This reverts commit ca00e4135baf91914222448f344bf986b7519454.
This PR reverts the fullscreenIntent option API due to OS limitations. Android devices will crash if the CallStyle notification Intent is not set to a fullScreenIntent. Therefore, this API, if used, will cause crashes.
- Revert the ability to toggle off the "fullscreenIntent" API.
- Manual testing with the test app.
N/A
=> Revert "[VBLOCKS-4627] Fullscreen Notification Permission API (#527)"

android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
This PR fixes a race condition in the preflightTest API in the Android native layer.
- Adjust promise to be resolved after the preflighttestrecord has been created.
- Locally ran e2e tests.
N/A
=> [VBLOCKS-5345] fix: runPreflight race condition

CHANGELOG.md, src/PreflightTest.ts, src/Voice.tsx, src/__mock-data__/PreflightTest.ts, src/__tests__/PreflightTest.test.ts, src/type/AudioCodec.ts
This PR fixes a discrepancy between iOS and Android such that the `isTurnRequired`, `warnings`, and `warningsCleared` members differed between platforms.
- `warnings` and `warningsCleared` are always arrays. Previously, if they were empty on iOS, they would be `undefined`.
- `isTurnRequired` was a string on iOS and now properly a boolean.
- Manual testing with test app.
N/A
=> [VBLOCKS-5356] Fix platform report discrepancies
