twilio/twilio-voice-react-native

- README.md
[Description of the Pull Request]
- [Bulleted summary of changes]
- [eg. Updated documentation]
- [eg. Added audio device feature]
- [Bulleted summary of validation steps]
- [eg. Added new test]
- [eg. Manually tested with app]
> chore: adding npm badge

- .gitignore
- CHANGELOG.md
- test/app/android/app/build.gradle
- test/app/android/app/src/debug/AndroidManifest.xml
- test/app/android/app/src/main/AndroidManifest.xml
- test/app/android/app/src/main/res/values/styles.xml
- test/app/android/build.gradle
- test/app/android/gradle.properties
- test/app/android/gradlew
- test/app/android/gradlew.bat
- test/app/android/settings.gradle
- test/app/ios/Podfile
- test/app/package.json
- test/app/src/hook.ts
- test/app/yarn.lock
Upgrade RN using this tool https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.66.5
- Use tool and manually diff the files, update files where necessary for Android.
- Launch the app on Android.
N/A
> [VBLOCKS-1239] Upgrade React Native

- README.md
- ios/TwilioVoicePushRegistry.m
- ios/TwilioVoiceReactNative+CallKit.m
- ios/TwilioVoiceReactNative.m
iOS clean up and documentation update
- Code cleanup
- Add PushKit/CallKit requirement documentation and sample code to README
- CircleCI
> VBLOCKS-1145 iOS clean up and documentation update

- android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
- api/voice-react-native-sdk.api.md
- ios/TwilioVoiceReactNative+CallKit.m
- ios/TwilioVoiceReactNative.h
- ios/TwilioVoiceReactNative.m
- src/Voice.tsx
- src/__mocks__/common.ts
- src/__tests__/Voice.test.ts
- src/common.ts
- src/error/UnsupportedPlatformError.ts
- src/type/NativeModule.ts
- test/app/src/hook.ts
New connect parameter for CallKit contact handle
- Add an optional parameter to Voice.connect() for supporting CallKit contact handle
- Update Android SDK
- Update iOS SDK to pass the value all the way to CallKit
- Update API doc
- CircleCI
> VBLOCKS-1320 New connect parameter for CallKit contact handle

- README.md
Doc updates to satisfy PRD requirements.
> Polish up readme

- CHANGELOG.md
> add link to reference app

- README.md
add a circle ci passing or failing badge to readme
> docs: readme circleci badge

- CHANGELOG.md
- README.md
Update `CHANGELOG.md` and `README.md` to reflect latest changes.
N/A
N/A
N/A
> docs: update changelog and readme for 1.0.0-rc7

- CHANGELOG.md
- README.md
Update documentation files for `beta.3` release.
- Update CHANGELOG.md to set a release date.
- Update README.md to point to the latest API docs.
- N/A
N/A
> chore: Update docs for beta.3 release

- api/voice-react-native-sdk.api.md
- src/Voice.tsx
- src/__tests__/Voice.test.ts
> VBLOCKS-1965: Make the selected device info's type consistent across APIs.

- api/voice-react-native-sdk.api.md
- src/Voice.tsx
- src/__tests__/Voice.test.ts
- src/type/common.ts
> VBLOCKS-1484: custom parameters supports only string values

- api/voice-react-native-sdk.api.md
- src/Call.tsx
- src/Voice.tsx
> VBLOCKS-1677 Move Voice's generic event type definitions to the end.

- CHANGELOG.md
- android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java
- android/src/main/java/com/twiliovoicereactnative/IncomingCallNotificationService.java
- android/src/main/java/com/twiliovoicereactnative/Storage.java
- android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
- android/src/main/java/com/twiliovoicereactnative/VoiceBroadcastReceiver.java
Fixed so that active call notifications are put up when user accepts call from application.
- Cleaned up flow so that there is only one path for accepting calls, through the service.
- Fixed bug where accepting a call from JS caused the In-Call notification to not show up.
- tested
None
> Fixed active call notification

- test/app/src/hook.ts
Fix the test app.
- Only invoke iOS specific functionality on iOS platforms.
- Tested with the test app.
N/A
> fix: only invoke ios specific function on ios

- .release.json
Remove reference to obsolete missing file in release script.
- Remove step from release scripts.
- N/A
N/A
> fix: remove missing file from release scripts

- android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
Fixed bug filed by QA
- Fixed bug where a null call-object was being marshalled
- Ran test with test app
None
> VBLOCKS-2503: getCalls results in an error upon incoming calls

- CHANGELOG.md
Updated changelog
- Updated changelog
n/a
None
> VBLOCKS-2558: Updated changelog to reflect upcoming release

- CHANGELOG.md
- docs/migration-guide-beta.4.md
Added a migration guide for the up coming beta.4 release.
- Added migration guide for beta.4 release
- Updated changelog
n/a
None
> VBLOCKS-2560: Migration guide for beta.4 release

- .release.json
- README.md
Automatically updating latest tag
- Add updating latest tag to release script
- Updating existing doc links
- Tested locally
- Tested using release process. See rc20
> VBLOCKS-2549 Tagging latest release automatically

- .circleci/config.yml
- package.json
- test/TwilioVoiceReactNativeExample/.detoxrc.js
- test/TwilioVoiceReactNativeExample/android/app/build.gradle
- test/TwilioVoiceReactNativeExample/android/app/src/androidTest/java/com/example/twiliovoicereactnative/DetoxTest.java
- test/TwilioVoiceReactNativeExample/android/app/src/main/AndroidManifest.xml
- test/TwilioVoiceReactNativeExample/android/app/src/main/res/xml/network_security_config.xml
- test/TwilioVoiceReactNativeExample/android/build.gradle
- test/TwilioVoiceReactNativeExample/e2e/jest.config.js
- test/TwilioVoiceReactNativeExample/e2e/starter.test.js
- test/TwilioVoiceReactNativeExample/package.json
- test/TwilioVoiceReactNativeExample/src/App.tsx
- test/TwilioVoiceReactNativeExample/yarn.lock
This PR adds Detox to the upgraded test app and adds CircleCI jobs to build and test on iOS and Android.
- Add Detox package and configurations to the upgraded test app.
- Add or adjust CircleCI pipelines to run the upgraded test app.
- Locally Detox runs.
- CircleCI Detox runs.
N/A
> [VBLOCKS-2553] Upgrade test app detox

- .circleci/config.yml
- package.json
- test/scripts/common.mjs
- test/scripts/gen-token.js
- test/scripts/gen-token.mjs
- yarn.lock
This PR is part of the work for VBLOCKS-2554: writing Detox tests for the upgraded test app. This PR creates a token minting script to be used in the CircleCI pipeline and is a drop in replacement for the current mechanism.
- Create token vending script.
- Replace current CI mechanism with new script.
- Ran script locally.
- Ran on CircleCI to ensure the build still works.
N/A
> Testing token vending

- android/build.gradle
- android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java
- android/src/main/java/com/twiliovoicereactnative/CallMessageListenerProxy.java
- android/src/main/java/com/twiliovoicereactnative/ReactNativeArgumentsSerializer.java
- android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
https://issues.corp.twilio.com/browse/VBLOCKS-2745
Emit CallInfo with `onMessageReceived` for Android
Functionality similar to iOS [Reference PR](https://github.com/twilio/twilio-voice-react-native/pull/302/files#diff-d7c22a29805bd13aed4721513833fe4e260df3321d6b94464979cf0221402ba0R21)
- Call: messageSent, messageError, messageReceived
- CallInvite: messageSent, messageError, messageReceived
> [VBLOCKS-2745] feat: emit callinfo

- CHANGELOG.md
This PR adds a changelog entry for the feature branch.
- Add changelog entry and links to API docs.
- N/A
N/A
> [VBLOCKS-2478] Call invite events changelog

- test/app/e2e/call.test.ts
This PR updates the call quality warning test to act on the UI to load unvirtualized event log elements.
- Add polling to the call quality warning test.
- Add swipe action to load all elements in the virtualized event log list.
- Manually ran Detox locally.
N/A
> fix: call quality warning test

- android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java
[VBLOCKS-2857](https://issues.corp.twilio.com/browse/VBLOCKS-2857)
- set call on ringing
- manual testing
> [VBLOCKS-2857] feat: Set call during ringing

- COMMON_ISSUES.md
- README.md
- docs/getting-started.md
This PR adds new documentation to help users get up and started quicker and with less friction.
- Getting Started docs.
- N/A
N/A
> [VBLOCKS-2891] Getting started docs

- README.md
- docs/customize-notifications.md
This PR adds documentation that details how to customize notifications on each platform.
- Add markdown doc detailing notification customizations.
- N/A
N/A
> [VBLOCKS-2938] Notification customization docs

- android/src/main/java/com/twiliovoicereactnative/JSEventEmitter.java
Fixed bug where float values were not being marshaled to JS.
- Fixed marshaling issue and tested with softphone test app
- Ran tests
None
> Fixed javascript marshaling error when floats are used

- test/app/e2e/common/twilioClient.ts
- test/app/e2e/suites/call.test.ts
- test/app/e2e/suites/callMessage.test.ts
This PR increases test coverage for the call message feature.
- Add new tests.
- Ran tests locally.
N/A
> [VBLOCKS-2965] Increase call message e2e coverage

- android/src/main/java/com/twiliovoicereactnative/CallRecordDatabase.java
- android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
- android/src/main/java/com/twiliovoicereactnative/VoiceService.java
- api/voice-react-native-sdk.api.md
- src/CallInvite.tsx
- src/CallMessage/CallMessage.ts
- src/Voice.tsx
- src/__tests__/CallInvite.test.ts
- src/__tests__/Voice.test.ts
- src/type/NativeModule.ts
- test/app/src/hook.ts
This PR introduces the JS API and the opt-in feature for CallMessaging for the Android platform.
- Add JS API.
- Add unit tests.
- Compiles locally with the Android RC.
This PR is to be merged to a feature branch and then re-tested thoroughly using a full Android release instead of an RC when that is available.
> [VBLOCKS-2930] Call message opt in feature for Android

- ios/TwilioVoiceReactNative+CallMessage.m
This PR implements a delay to fix race conditions for callmessage failure events.
- Add delay to emission of callmessage failure events.
- Manually tested on iOS device.
N/A
> [VBLOCKS-3258] fix(ios): add delay to prevent race condition

- ios/TwilioVoiceReactNative+CallKit.m
- ios/TwilioVoiceReactNative.h
- ios/TwilioVoiceReactNative.m
This PR implements the iOS portion of the CallMessage opt-in feature. Thanks @bobiechen-twilio for the assist!
- Add opt-in feature for iOS.
- Manually tested with test app.
N/A
> [VBLOCKS-3285] Call Messaging Opt in feature ios

- CHANGELOG.md
This PR retracts the eventing 1.x GA from our changelog. The GA will come at a future point in time.
- Amend changelog entry for accuracy.
- N/A
N/A
> docs: amend changelog for 1.1.0-rc1

- CHANGELOG.md
- test/app/ios/Podfile.lock
This PR moves a changelog entry from `1.1.0` (where it incorrectly resides) to `1.1.1`.
- Move changelog bullet point.
- N/A
N/A
> docs: fix changelog

- CHANGELOG.md
- android/build.gradle
- api/voice-react-native-sdk.api.md
- scripts/errors.js
- src/error/generated.ts
- test/app/e2e/suites/callMessage.test.ts
- test/app/ios/Podfile.lock
- twilio-voice-react-native.podspec
This PR pulls the latest native SDK versions and adds the 31212 error code to be generated.
- Add 31212 error code to generated list.
- Add generated error to repo.
- Pull native SDKs that use the new error.
- Manually tested with Test App.
N/A
> [VBLOCKS-3288] 31212 error code

- .circleci/config.yml
This PR updates the CircleCI image that is used for Android testing.
- Change Android CI image and adjust configuration and test steps to work for the RN Test App.
- CI passing.
N/A
> [VBLOCKS-2907] Update Android CI image

- package.json
- src/Call.tsx
- src/CallInvite.tsx
- src/Voice.tsx
- src/type/CallKit.ts
This PR fixes some API docstrings to reduce build warnings. Some warnings are unavoidable.
- Adjust package configuration for eslint.
- Fix some API docstrings.
- Ran docs pipeline locally.
N/A
> [VBLOCKS-3135] Fix api docs build warnings

- CHANGELOG.md
- KNOWN_ISSUES.md
- README.md
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/twiliovoicereactnative/ConfigurationProperties.java
- android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
- android/src/main/java/com/twiliovoicereactnative/VoiceApplicationProxy.java
- android/src/main/java/com/twiliovoicereactnative/VoiceFirebaseMessagingService.java
- android/src/main/res/values/config.xml
- android/src/main/res/values/strings.xml
- api/voice-react-native-sdk.api.md
- docs/out-of-band-firebase-messaging-service.md
- src/Voice.tsx
- src/__mocks__/common.ts
- src/__tests__/Voice.test.ts
- src/type/NativeModule.ts
This PR adds APIs to allow users to disable the built in firebase service.
- Add opt-out configuration and feature to the SDK.
- Add documentation for this feature and its use-cases.
- Manually tested locally with a 3rd party firebase messaging library.
N/A
> [VBLOCKS-3510] Allow for disabling of built-in firebase service

- README.md
- docs/getting-started-android-java.md
- docs/getting-started-android-kotlin.md
- docs/getting-started-ios.md
This PR reorganizes our docs for readability and usability.
- Reorganize our readme.
- Split our getting started document into platform and language specific files.
- N/A
The documents in this PR will be duplicated (?) in the TwilioDotCom docs for better readability.
> [VBLOCKS-3505] docs: update readme and getting started docs

- android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java
- src/Voice.tsx
This PR addresses feedback from the QE team for rc1. This PR fixes crashes on empty string values and incorrect api docs.
- Fix crashes on empty strings.
- Fix api docs.
- Manual testing.
N/A
> [VBLOCKS-3848] fix: address rc feedback

- docs/expo/ios.md
This PR documents what an Expo config plugin would do for the iOS platform and basic steps on how to implement one.
- N/A
- N/A
N/A
> [VBLOCKS-4072] docs: ios expo config plugin

- docs/expo/android.md
This PR documents how an Expo Config Plugin can be used to introduce Expo support for Android platforms.
- Write out general steps for creating and using an Expo Config Plugin to get Expo support working in this library.
- N/A
N/A
> [VBLOCKS-3831] Document expo support android config plugin

- docs/expo/getting-started-expo.md
This PR adds a very brief overview document to the Expo folder to help direct users to the proper documentation.
- N/A
- N/A
N/A
> docs: add expo overview

- COMMON_ISSUES.md
This PR updates the `COMMON_ISSUES.md` doc to refer to the new Expo guide.
- Update COMMON ISSUES doc.
- N/A
N/A
> fix: Update COMMON_ISSUES.md

- CHANGELOG.md
Add the potential error and solution to the changelog.
- Add useful info to changelog.
- N/A
N/A
> [VBLOCKS-3981] fix: add potential error code to the changelog

- CHANGELOG.md
This PR moves the NewArch changelog entry into the proper version `1.6.0`.
- Rearrange changelog entry.
- N/A
N/A
> [VBLOCKS-3981] Fix changelog for NewArch support

- android/src/main/java/com/twiliovoicereactnative/TwilioVoiceReactNativeModule.java
- api/voice-react-native-sdk.api.md
- src/PreflightTest.ts
- src/common.ts
- src/index.tsx
- src/type/AudioCodec.ts
- src/type/CallOptions.ts
- src/type/Ice.ts
- src/type/NativeModule.ts
- test/app/src/hook.ts
This PR fixes the get state implementation on the native Android layer.
- Use the common constants to translate the native preflight test state to the expected constant for the JS layer to interpret.
- Manually tested with test app
N/A
> Preflight fix android state

- src/__tests__/PreflightTest.test.ts
This PR adds PreflightTest unit tests for private methods.
- Add unit tests for PreflightTest module for private methods.
- Run unit test suite.
N/A
> [VBLOCKS-5220] feat: preflight private method unit tests

- src/__tests__/PreflightTest.test.ts
This PR creates the unit tests for the PreflightTest public methods.
- Add unit tests.
- Ran unit tests.
N/A
> [VBLOCKS-5022] Preflight unit tests public methods

- src/Voice.tsx
- src/__mocks__/common.ts
- src/__tests__/PreflightTestOptions.test.ts
- src/__tests__/Voice.test.ts
- src/utility/preflightTestOptions.ts
This PR adds option validation for the RN SDK preflightTest feature.
- Add helper function to validate the PreflightTest options.
- Unit tests.
- Manually ran with test app.
N/A
> [VBLOCKS-5379] feat: add runPreflight option validation
